name: Deploy Backend (Next.js API)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      # 실제 배포는 Render, Vercel, AWS 등 서비스에 맞게 추가 필요
      - name: Deploy (example)
        run: echo "Add your deployment step here (e.g., vercel --prod, rsync, etc.)" 