name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npx tsc --noEmit
      - name: Test
        run: npm test
      - name: Build user app
        run: npm run build --workspace=apps/user
      - name: Build admin app
        run: npm run build --workspace=apps/admin

  # 배포 예시 (Vercel, Netlify, AWS 등)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Deploy to Vercel
  #       run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
