name: Deploy to GitHub Pages & Build Docker

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/user
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/user/dist

  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/user
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t user-app:latest .
